# Site settings
title: Dynamical Systems and AI Research Group
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/Dynamical-Systems" # the subpath of your site, e.g. /blog/
url: "sgavir8738.github.io" # the base hostname & protocol for your site

linkedin_username: vignar
researchgate_username: Vignesh-Narayanan
googlescholar_url: rirGB10AAAAJ

# Build settings
markdown: kramdown
